### ISSUE TITLE
Training issue for MLP models

### ISSUE THREAD

**Issue by alexzli** [Oloren-AI/olorenchemengine#39]
It should be made clear that `TorchMLP` and `MLP` models are not designed for regression in the documentation.

**Comment by davidzqhuang** [comment]
Thanks for opening an issue!

What do you mean by this? Below is an example of TorchMLP used in regression

```
import olorenchemengine as oce
dataset = oce.BACEDataset()
print(dataset.train_dataset)
model = oce.TorchMLP(oce.DescriptastorusDescriptor("morgan3counts"))
model.fit(*dataset.train_dataset)
```

If you are having issues running this snippet, to help better diagnose the issue, please include your OCE version, a printout of the `conda list` or `pip list`, operating system and version, and hardware accelerator if applicable.
