### ISSUE TITLE
Error running 0_Minimal_Example.ipynb

### ISSUE THREAD

**Issue by PatWalters** [Oloren-AI/olorenchemengine#49]
I got an error when running 
results = model.predict(dataset.test_dataset[0], return_ci = True, return_vis = True) in 0_Minimal_Example.ipynb
This was based on an install I did a few minutes ago on an M1 Mac

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
Cell In [8], line 1
----> 1 results = model.predict(dataset.test_dataset[0], return_ci = True, return_vis = True)

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/base_class.py:599, in BaseModel.predict(self, X, return_ci, return_vis, skip_preprocess, **kwargs)
    597 assert self.em_status == "fitted", "error model not fit"
    598 result = pd.DataFrame({"predicted": result})
--> 599 errors = self.error_model.score(X_original)
    600 if return_ci:
    601     result["ci"] = errors

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/base_class.py:1279, in BaseErrorModel.score(self, X)
   1276 assert hasattr(self, "reg"), "error model not yet fitted"
   1278 y_pred = np.array(self.model.predict(X)).flatten()
-> 1279 scores = self.calculate(X, y_pred)
   1281 return self.reg(scores)

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/uncertainty.py:356, in TrainDistKNN.calculate(self, X, y_pred)
    353         return np.sqrt(np.mean(residuals[idxs]))
    354     return np.sqrt(np.dot(similarity[idxs], residuals[idxs]) / np.sum(similarity[idxs]))
--> 356 return np.array([dist(smi) for smi in tqdm(X)])

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/uncertainty.py:356, in <listcomp>(.0)
    353         return np.sqrt(np.mean(residuals[idxs]))
    354     return np.sqrt(np.dot(similarity[idxs], residuals[idxs]) / np.sum(similarity[idxs]))
--> 356 return np.array([dist(smi) for smi in tqdm(X)])

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/uncertainty.py:349, in TrainDistKNN.calculate.<locals>.dist(smi)
    347 def dist(smi):
    348     mol = Chem.MolFromSmiles(smi)
--> 349     ref_fp = AllChem.GetMorganFingerprint(mol, 2)
    350     similarity = np.array(BulkTanimotoSimilarity(ref_fp, self.train_fps))
    351     idxs = np.argsort(similarity)[-self.k:]

ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.GetMorganFingerprint(NoneType, int)
did not match C++ signature:
    GetMorganFingerprint(RDKit::ROMol mol, unsigned int radius, boost::python::api::object invariants=[], boost::python::api::object fromAtoms=[], bool useChirality=False, bool useBondTypes=True, bool useFeatures=False, bool useCounts=True, boost::python::api::object bitInfo=None, bool includeRedundantEnvironments=False)

**Comment by davidzqhuang** [comment]
Looking into this.

**Comment by davidzqhuang** [comment]
Hmm, this one is a bit odd. I reinstalled with the previous workflow on my M1 Mac and re-ran the notebook with no issues.

By any chance are you running this script with a different dataset? This seems like it's due to some SMILES which could not be converted in RDKit.

Perhaps try it with this line to diagnose whether or not definitely valid SMILES works
`results = model.predict(["CC(=O)Nc1ccc(cc1)O", "CC(=O)OC1=CC=CC=C1C(=O)O"], return_ci = True, return_vis = True)`

If so and if on a different dataset, perhaps try filtering the SMILES for validity.

**Comment by PatWalters** [comment]
I was running the default dataset.  
The problem appears to be that a dataframe was being passed rather than a list of SMILES.  I changed the code to 
results = model.predict(dataset.test_dataset[0].Smiles.values, return_ci = True, return_vis = True)
and everything worked.

**Comment by davidzqhuang** [comment]
Very odd, thank you so much for debugging. 

The data frame input should be handled as well, so I’ll take a look at that maybe it’s Pandas versioning.

**Comment by davidzqhuang** [comment]
New version of UQ needed to call SMILESRepresentation for multiple types but didn't. Fixed in PR #52.

Thank you so much for reporting this.
