### ISSUE TITLE
bug in 2A_Confidence_Intervals.ipynb

### ISSUE THREAD

**Issue by PatWalters** [Oloren-AI/olorenchemengine#53]
The line 
testSDC.fit(dataset.valid_dataset[0], dataset.valid_dataset[1])
throws an exception.  It works if changed to 
testSDC.fit(dataset.valid_dataset[0].smiles.values, dataset.valid_dataset[1].values)

**Comment by PatWalters** [comment]
Error on testSDC.fit_cv()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [18], line 1
----> 1 testSDC.fit_cv()

File ~/opt/anaconda3/envs/oce/lib/python3.8/site-packages/olorenchemengine/base_class.py:1148, in BaseErrorModel.fit_cv(self, n_splits, **kwargs)
   1145 scores = None
   1146 kf = KFold(n_splits=n_splits)
-> 1148 for train_index, test_index in kf.split(X):
   1149     X_train, X_test = self.X_train[train_index], self.X_train[test_index]
   1150     y_train, y_test = self.y_train[train_index], self.y_train[test_index]

NameError: name 'X' is not defined

**Comment by PatWalters** [comment]
Error similar to above on 
testSDC.score(dataset.test_dataset[0]
fixed with 
testSDC.score(dataset.test_dataset[0].smiles)

**Comment by PatWalters** [comment]
testADAN = oce.BaseADAN(criteria='E_raw')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [19], line 1
----> 1 testADAN = oce.BaseADAN(criteria='E_raw')
      2 testADAN.build(model, dataset.train_dataset[0], dataset.train_dataset[1])

AttributeError: module 'olorenchemengine' has no attribute 'BaseADAN'

**Comment by PatWalters** [comment]
models = [oce.SDC(), oce.wRMSD1(), oce.wRMSD2(), oce.PREDICTED()]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [21], line 1
----> 1 models = [oce.SDC(), oce.wRMSD1(), oce.wRMSD2(), oce.PREDICTED()]

AttributeError: module 'olorenchemengine' has no attribute 'wRMSD1'

**Comment by davidzqhuang** [comment]
Thanks, I think the cause of the errors that need .smiles.values is the same as the cause of the similar bug in Example 0. For the other errors, I'm looking into them. I suspect it may be that the tutorials weren't updated when we did a UQ refresh. Should be naming convention issues, will fix them.

PR #52 attempts to address the .smiles.values errors.

You can apply the patch in PR #52 by copy-pasting the file [uncertainty.py.zip](https://github.com/Oloren-AI/olorenchemengine/files/9895969/uncertainty.py.zip) into the right path, i.e. it's "~/miniconda3/lib/python3.9/site-packages/olorenchemengine/uncertainty.py" for me. We'll patch the pypi version as soon as we can.

The following command should also work

pip install --upgrade "olorenchemengine[full] @ git+https://github.com/Oloren-AI/olorenchemengine.git"

**Comment by davidzqhuang** [comment]
The errors are because the 2 series of examples have been made out of date with our newest changes in UQ methods, will update this issue again when I've updated all of them

**Comment by davidzqhuang** [comment]
All these errors have been fixed, also audited 2A-E for all UQ-related errors.

Main issues were due to compatibility between old UQ system + tutorials and the new UQ system.

@alexzli please take a look as well

**Comment by PatWalters** [comment]
This one works for me now, thanks!  
It might be useful to include a reference to SDN in 2A_Confidence_Intervals.ipynb.
