### ISSUE TITLE
Unstable performance with oce model

### ISSUE THREAD

**Issue by XZhang-ML** [Oloren-AI/olorenchemengine#74]
It's really nice software, thanks for all the efforts! 
one problem I noticed is that the model initiates with different seeds and let to different performances per run. 
Could you add a random state to the model parameter so the prediction is reproducible?

**Comment by davidzqhuang** [comment]
This is something that we wish to add at some point, but will likely take a bit of time to follow through on the development of this.

Mainly because given the amount of dependencies/ packages in use, we would need to standardize across all of them (if that is even possible).
