### ISSUE TITLE
Unreasonable lower quantile line

### ISSUE THREAD

**Issue by hshany** [Oloren-AI/olorenchemengine#91]
Line 1123 of base_class.py gives unreasonable lower quantile points and line:

<img width="874" alt="Screen Shot 2022-12-29 at 5 02 19 PM" src="https://user-images.githubusercontent.com/25070026/209928837-10c560f9-c581-4e78-a490-9ef0806e790f.png">

**Comment by davidzqhuang** [comment]
Bug introduced by saving and loading quantile fit line, fixed by setting correct mode with fit_regression in #92
